language: java
jdk:
  - openjdk8

branches:
  only:
    - main
    - develop

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

notifications:
  email:
    recipients:
      - 'pkalsh345@gmail.com'
      - 'annyousung@gmail.com'