spring:
  profiles:
    active: local
---
#Local
server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/runmate?serverTimezone=Asia/Seoul&characterEncoding=utf8
    username: root
    password: 3504httdA*

  jpa:
    hibernate:
      ddl-auto: none #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
  config:
    activate:
      on-profile: "local"
  flyway:
    url: jdbc:mysql://localhost:3306/runmate?serverTimezone=Asia/Seoul&characterEncoding=utf8
    user: root
    password: 3504httdA*
    schemas: runmate
    encoding: UTF-8
    table: flyway_migration_history

kakao:
  requestCodeUrl: https://kauth.kakao.com/oauth/authorize
  requestTokenUrl: https://kauth.kakao.com/oauth/token
  requestUserInfoUrl: https://kapi.kakao.com/v2/user/me
  requestLogoutUrl: https://kapi.kakao.com/v1/user/logout
  restApiKey: db7c4047c9ed5887c5e4bf4e450e0ac2
  grantType: authorization_code
  responseType: code
  redirectUri: http://localhost:8080/api/auth/kakao/login

jwt:
  secretKey: 3q$.5pdz4563!2aghkz
  expire: 600000
---
#Prod
---

