spring:
  profiles:
    active: local
---
#Local
server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/runmate?serverTimezone=Asia/Seoul&characterEncoding=utf8
    username: root
    password: 3504httdA*

  jackson:
    property-naming-strategy: SNAKE_CASE

kakao:
  requestCodeUrl: https://kauth.kakao.com/oauth/authorize
  requestTokenUrl: https://kauth.kakao.com/oauth/token
  requestUserInfoUrl: https://kapi.kakao.com/v2/user/me
  requestLogoutUrl: https://kapi.kakao.com/v1/user/logout
  restApiKey: db7c4047c9ed5887c5e4bf4e450e0ac2
  grantType: authorization_code
  responseType: code
  redirectUri: http://localhost:8080/api/auth/kakao/login

jwt:
  secretKey: 3q$.5pdz4563!2aghkz
  expire: 600000
---
#Prod
---

