# common
spring:
  profiles:
    include:
      - core
  jackson:
    property-naming-strategy: SNAKE_CASE
server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

kakao:
  requestCodeUrl: https://kauth.kakao.com/oauth/authorize
  requestTokenUrl: https://kauth.kakao.com/oauth/token
  requestUserInfoUrl: https://kapi.kakao.com/v2/user/me
  requestLogoutUrl: https://kapi.kakao.com/v1/user/logout
  restApiKey: db7c4047c9ed5887c5e4bf4e450e0ac2
  grantType: authorization_code
  responseType: code
  redirectUri: http://localhost:8080/api/auth/kakao/login

jwt:
  secretKey: 3q$.5pdz4563!2aghkz
  expire: 600000

---
spring.config.activate.on-profile: local

---
spring.config.activate.on-profile: prod
