# common
server:
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  profiles:
    include:
      - core

---
spring.config.activate.on-profile: local
server:
  port: 8081

---
spring.config.activate.on-profile: prod
server:
  port: 6374
